site_name: Retrace
site_url: http://d0ugal.github.io/retrace/
site_description: Configurable retrying.
site_author: Dougal Matthews

theme: material

repo_name: 'GitHub'
repo_url: 'https://github.com/d0ugal/retrace'
copyright: <a href="http://www.dougalmatthews.com/">Dougal Matthews</a>


site_dir: build/docs

markdown_extensions:
    - toc:
       permalink: Â¶
    - admonition:
    - codehilite(css_class=code):

extra:
  version: !!python/object/apply:getattr
    - !!python/object/apply:__import__
      - 'retrace'
    - __version__
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  author:
    github: 'd0ugal'
    twitter: 'd0ugal'
